# Generated by Django 4.2 on 2025-03-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_idd',
            new_name='post',
        ),
    ]
