# Generated by Django 4.2 on 2024-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
    ]
