# Generated by Django 4.2 on 2025-01-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_securityguard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityGuard',
        ),
    ]
